// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { MerchantContract } from "./MerchantContract";

export class Events {
  static encode(message: Events, writer: Writer): void {
    const merchantContracts = message.merchantContracts;
    for (let i: i32 = 0; i < merchantContracts.length; ++i) {
      writer.uint32(10);
      writer.fork();
      MerchantContract.encode(merchantContracts[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Events {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Events();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.merchantContracts.push(
            MerchantContract.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  merchantContracts: Array<MerchantContract>;

  constructor(merchantContracts: Array<MerchantContract> = []) {
    this.merchantContracts = merchantContracts;
  }
}
