// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class MerchantContract {
  static encode(message: MerchantContract, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.merchantAddress);

    writer.uint32(18);
    writer.string(message.pointsContract);
  }

  static decode(reader: Reader, length: i32): MerchantContract {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MerchantContract();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.merchantAddress = reader.string();
          break;

        case 2:
          message.pointsContract = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  merchantAddress: string;
  pointsContract: string;

  constructor(merchantAddress: string = "", pointsContract: string = "") {
    this.merchantAddress = merchantAddress;
    this.pointsContract = pointsContract;
  }
}
