[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.starknet-testnet]
protocol = "substreams"
shard = "primary"
provider = [
    { label = "substreams", details = { type = "substreams", url = "https://starksepolia.substreams.pinax.network:443", token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FwaS5hY2NvdW50LnBpbmF4Lm5ldHdvcmsvdjEvIiwic3ViIjoiY2Q1YTcxZDItOGU2Yi00ODAxLTgwODktMmI2OGFhNTNhMGU1IiwiYXVkIjpbImh0dHBzOi8vYWNjb3VudC5waW5heC5uZXR3b3JrLyJdLCJleHAiOjIwNDc5NjcwMTYsImlhdCI6MTczMjYwNzAxNiwiYXBpX2tleV9pZCI6ImNmODFhMDcxLTk3MWYtNDhjYS05OWQzLThkMWM1MjE0ZTM2NyJ9.CtPCdxpaDqFieRiQs-CqWmAx6bfq9xY3gMsSIKojQR4", features = [
        "compression",
        "filters",
    ], conn_pool_size = 1 } },
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]