// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantContract {
    #[prost(string, tag="1")]
    pub merchant_address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub points_contract: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub merchant_contracts: ::prost::alloc::vec::Vec<MerchantContract>,
}
// @@protoc_insertion_point(module)
