[package]
name = "contracts"
version = "0.1.1"
edition = "2024_07"

[dependencies]
starknet = "2.11.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }

[[target.starknet-contract]]
casm = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }

[scripts]
test = "snforge test"
